name: Build Android App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js (verifica la versione usata nel tuo progetto)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Setup Java 21 (richiesto da Capacitor 7)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 4️⃣ Installa dipendenze
      - name: Install dependencies
        run: npm ci

      # 5️⃣ Build del progetto web
      - name: Build web assets
        run: npm run build

      # 6️⃣ Sincronizza con Capacitor
      - name: Sync Capacitor
        run: npx cap sync android

      # 7️⃣ Build APK Android
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 8️⃣ Carica l'APK come artefatto su GitHub Actions
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk


