name: Android CI (Capacitor + Vite)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      JAVA_VERSION: '21'
      NODE_VERSION: '22'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Java (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Android SDK (cmdline-tools)
        run: |
          mkdir -p "$ANDROID_SDK_ROOT"
          cd "$ANDROID_SDK_ROOT"
          curl -sSLo cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          mkdir -p cmdline-tools/latest
          unzip -q cmdline-tools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/ || true
          rm -f cmdline-tools.zip
          echo "y" | cmdline-tools/latest/bin/sdkmanager --licenses
          cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      - name: NPM install
        run: npm ci || npm i

      - name: Build web (Vite -> www/)
        run: npm run build

      - name: Capacitor sync
        run: npx cap sync android

      - name: Gradle assembleDebug
        working-directory: android
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          JAVA_TOOL_OPTIONS: "-Xmx1g"
          GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx1g -Dfile.encoding=UTF-8' -Dorg.gradle.daemon=false"
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/*.apk
          compression-level: 0
