name: Android CI (Capacitor + Vite)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      # Usa UN SOLO percorso: quello di default del runner
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_VERSION: '21'
      NODE_VERSION: '22'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Java (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Android SDK (api 35 + build-tools 35.0.0)
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: 35.0.0
          # facoltativo: ndk: 26.3.11579264

      - name: NPM install
        run: npm ci || npm i

      - name: Build web (Vite -> www/)
        run: npm run build

      - name: Capacitor sync
        run: npx cap sync android

      - name: Create local.properties (sdk.dir)
        run: |
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          cat android/local.properties

      - name: Gradle assembleDebug
        working-directory: android
        env:
          JAVA_TOOL_OPTIONS: "-Xmx1g"
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8 -Dorg.gradle.daemon=false"
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/*.apk
          compression-level: 0
          
