name: Build Capacitor Android App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3️⃣ Setup Java 17 (compatibilità Gradle/Android)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 4️⃣ Install dependencies con legacy-peer-deps
      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      # 5️⃣ Installa Capacitor Android e plugin Speech Recognition
      - name: Install Capacitor Android & Plugins
        run: |
          npm install @capacitor/android --legacy-peer-deps
          npm install @capacitor-community/speech-recognition --legacy-peer-deps

      # 6️⃣ Build progetto web
      - name: Build project
        run: npm run build

      # 7️⃣ Aggiungi o sincronizza Android (crea piattaforma se non esiste)
      - name: Add or Sync Android
        run: |
          npx cap add android || npx cap sync android

      # 8️⃣ Controllo permessi microfono
      # Percorso locale: android/app/src/main/AndroidManifest.xml
      # Deve contenere dentro <manifest>:
      # <uses-permission android:name="android.permission.RECORD_AUDIO" />
      # Puoi aggiungerlo manualmente prima del push, oppure assicurarti che sia già presente nel repo

      # 9️⃣ Build APK
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 🔟 Upload artifact (APK debug)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
