name: Android Debug APK

on:
  push:
    branches: [ "feat/biometrics" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci

      - name: Build web (Vite -> www)
        run: npm run build

      - name: Capacitor sync android (include Cordova plugins)
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Android debug APK
        working-directory: android
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: walleet-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
